### PR TITLE
Feature/reset value on disable by config

### PR DESCRIPTION
**Pull request by icrc-agomes**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.

## Summary
This PR gives us the ability when we want to disable a field, to have the possibility to chose not to reset its value.
This can be done throw the configuration using the prop  `resetValueOnDisable`. 

The development was made having in mind that the default behavior is for the value to be reset. So, if we have a field with the `disable` prop and we lack the `resetValueOnDisable` the input to be disabled will reset its value.

## Screenshots
image

https://github.com/openmrs/openmrs-ngx-formentry/assets/106243905/824b0a04-2d46-4f9c-be0d-ee579c7e4ebd

As you can see the _datepicker_ has the normal behaviour, resets the value on disable, the others don't because of the changes made.

### CODE REVIEW

**Comment by denniskigen** [comment]
Hey Andre, could you please give us more context about this one? A GIF/video of the before and after would be super helpful for reviewers.

**Comment by icrc-agomes** [comment]
> Hey @icrc-agomes @icrc-fdeniger, could you please give us more context about this one? A GIF/video of the before and after would be super helpful for reviewers.

**Comment by icrc-agomes** [comment]
> Hey @icrc-agomes @icrc-fdeniger, could you please give us more context about this one? A GIF/video of the before and after would be super helpful for reviewers.

@denniskigen I have updated the comment section and added a video showing the behaviour that changed and a caption below explaining.

**Review by ibacher — CHANGES_REQUESTED** [review]
I'm a little worried about the number of unrelated changes that seem to be in this PR. Also, it looks like it's out of date (and has conflicts with) the latest `main` branch of this repo. Can you please update this to merge in the latest version and resolve the conflicts?

The comments I left on one instance apply to the other, similar cases. Thanks for this!

**Pull request closed without merging**
