### PR TITLE
(feat) Add form navigation links

### PR DESCRIPTION
**Pull request by denniskigen**
# Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR introduces navigation links to the form renderer UI, addressing feedback from the Palladium team during their recent user acceptance testing process. Users requested a way to navigate between pages without scrolling up to the top of the page to select the next tab from the navigation menu. This solution has not undergone a design review process with the design team but serves as a temporary measure to alleviate this issue while we iterate towards a more comprehensive solution.

## Screenshots

https://github.com/openmrs/openmrs-ngx-formentry/assets/8509731/cc5facf6-f6b0-442b-8bb0-e4c054d8aff2

## Related Issue
*None*

## Other

This UI was inspired by [Carbon's](https://carbondesignsystem.com/all-about-carbon/what-is-carbon/) navigation UI (found just above the footer on each page).

### CODE REVIEW

**Comment by denniskigen** [comment]
Not sure why the translation strings aren't getting picked up - if you look at the video, it appears that it's just the (lowercase) keys that are getting rendered in the navigation buttons. Maybe I'm missing something, @vasharma05?

**Comment by ibacher** [comment]
@denniskigen I don't think the `extract-i18n` job was ever made to work. It tries to use `@angular/localize` rather than `ngx-translate`. We'd have to look at getting [this project](https://github.com/biesbjerg/ngx-translate-extract) integrated. 

However, the other thing is that the translations are loaded at the application level rather than the library level, so it's not as if translations extracted in this project are that useful (we ultimately use the JSON files included in the patient chart, not the ones in `src`, which are primarily for testing. (This is made somewhat awkward by the fact that we do include strings to translate in the library).

**Comment by denniskigen** [comment]
Thanks for clarifying things, @ibacher. Does it mean that the translation keys and strings I've provided as part of this PR are sufficient?

**Comment by ibacher** [comment]
@denniskigen Yes, that should be sufficient.

**Review by donaldkibet — APPROVED** [review]

**Pull request merged**
