### PR TITLE
(fix) Update radio selected option on value modification

### PR DESCRIPTION
**Pull request by icrc-psousa**
## Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.

## Summary
Fixed radio component not updating when it's value modification is triggered by another component

### CODE REVIEW

**Comment by icrc-psousa** [comment]
@ibacher @enyachoke Would you be able to review this or to assign the proper reviewers. Thanks!

**Comment by delphinepas** [comment]
@denniskigen would it be possible to get this reviewed? cc @icrc-psousa @icrc-fdeniger

**Comment by denniskigen** [comment]
Hi @icrc-psousa, mind sharing an example of a situation where a component might trigger modification of the value of a radio component?

**Comment by icrc-psousa** [comment]
> Hi, @icrc-psousa, mind sharing an example of a situation where a component might trigger modification of the value of a radio component?

Hi @denniskigen, we have, for instance, these forms where the last question (prior to the regression fixed by this PR) was automatically being updated to "Complete" once all the above questions were answered. Currently, the last field is editable but it could be read only, requiring no input from the user as it's automatically marked as "complete"

image

**Review by denniskigen — APPROVED** [review]

**Pull request merged**
