### PR TITLE
(fix) Remove hidden fields from patient identifier question types

### PR DESCRIPTION
**Pull request by donaldkibet**
# Requirements

- [ ] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR filters out hidden questions when generating patient identifiers.

### CODE REVIEW

**Review by makombe — APPROVED** [review]
LGTM

**Comment by ojwanganto** [comment]
cc @denniskigen

**Review by denniskigen — APPROVED** [review]

**Comment by denniskigen** [comment]
LGTM! Thanks, @donaldkibet.

**Comment by ojwanganto** [comment]
Thanks @denniskigen

**Pull request merged**
