### PR TITLE
(fix) O3-2763: Fix overflow issue affecting multi-select fields

### PR DESCRIPTION
**Pull request by elimm**
# Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary
In cases where the form contains only one or several fields and the last of them is a multi-select, the dropdown is cut off and an unnecessary scroll appears. This PR prevents form page collapsing.

### STR on Dev3
Open the `Repeating Sample Form `/ `Second Page`

## Screenshots
image
image

## Related Issue
[O3-2763](https://openmrs.atlassian.net/browse/O3-2763)

### CODE REVIEW

**Comment by denniskigen** [comment]
Hi, @elimm, thanks for the PR. I'm unable to reproduce the issue on my end and I'd like to know:

- You can reproduce this on dev3
- What schema you're using

Here's the experience I'm getting with the lab test order form on dev3:

https://github.com/openmrs/openmrs-ngx-formentry/assets/8509731/31e63253-4325-43c3-8074-e803988e784f

I couldn't replicate the issue when running this library locally either.

**Comment by elimm** [comment]
Hi @denniskigen. I reproduced the bug on Dev3. You can easily check this when you open the `Repeating Sample Form` / `Second Page`
image

**Comment by elimm** [comment]
We are using esm-form-entry-app v6.1.0 with some minor changes unrelated to this issue.

**Comment by denniskigen** [comment]
Thanks, @elimm, I'm able to replicate.

**Comment by elimm** [comment]
I saw this `oveflow-x` property and removing it solves the problem for our forms, but I don't know the reason why it was added and whether it will break other forms, so I chose the height inheritance option, yes it looks ugly, but it does the trick. If you would prefer to remove the `oveflow-x` property, I'll do so.

**Comment by denniskigen** [comment]
It was introduced in https://github.com/openmrs/openmrs-ngx-formentry/pull/98. I've tested things with a few forms and I'm inclined to think we can safely remove it, @elimm.

**Comment by elimm** [comment]
@denniskigen Done. I closed [this PR](https://github.com/openmrs/openmrs-esm-patient-chart/pull/1619) as unnecessary

**Comment by denniskigen** [comment]
Cool. Thanks for flagging this issue and working on it, @elimm!

**Review by denniskigen — APPROVED** [review]

**Pull request merged**
