### PR TITLE
(chore) Version bumps and fixes post Angular 14 upgrade

### PR DESCRIPTION
**Pull request by denniskigen**
# Requirements

- [x] This PR has a title that briefly describes the work done, including the ticket number if there is a ticket.
- [ ] My work conforms to the [OpenMRS 3.0 Styleguide](https://om.rs/styleguide) and [design documentation](https://zeroheight.com/23a080e38/p/880723-introduction).
- [ ] My work includes tests or is validated by existing tests.

## Summary

This PR makes additional version bumps and fixes following the Angular 14 migration in #88. More specifically, it:

- Bumps the versions of the following packages:
	- [@angular-extensions/elements](https://www.npmjs.com/package/@angular-extensions/elements)
	- [rxjs](https://www.npmjs.com/package/rxjs) (newer required as a peer dep of v14.x.x of @angular-extensions/elements)
	- [jasmine](https://www.npmjs.com/package/jasmine) and [karma](https://www.npmjs.com/package/karma) and their related packages (for testing)
	- [ng-packagr](https://www.npmjs.com/package/ng-packagr) (I've fixed the version range to only include backwards-compatible patch bumps)
- Bumps the versions of peer dependencies that the library expects. This should be what leads to errors or warnings in the applications that consume this library. Most Angular packages specified here were still pointing to v12. I've bumped them up to Angular 14.
- Removes `hammer.js` which is not getting used anywhere.
- Fixes some `RxJS` warnings post-version bump, specifically ones relating to the expected return value of `Subject`s and one relating to the use of the `merge` function, where I amended the return value of an observable to a `boolean` to match the expected contract.
- Fixes the `build:lib` task' in the `turbo` config file, escaping the colon in the job's name to fix a warning.
- Bumps `yarn` to the latest 1.x denoted version, v1.22.19. 		

## Screenshots

*None*

## Related Issue

*None*

## Other

*None*

### CODE REVIEW

**Comment by denniskigen** [comment]
Ok, this shouldn't go yet. Seeing some issues when linking to patient chart locally.

**Comment by ibacher** [comment]
Definitely leaving it alone this time 😁

**Comment by denniskigen** [comment]
I've whittled them down to just these two. Ideas welcome.

CleanShot 2023-10-12 at 1  13 02@2x

**Comment by denniskigen** [comment]
I'll try [these](https://github.com/angular/angular-cli/issues/22088) suggestions out tomorrow.

**Comment by ibacher** [comment]
Better question for @icrc-jofrancisco

**Comment by ibacher** [comment]
I wonder if the problem could be as simple as we’re trying to import `*.js` whereas those files now [seems to use](https://github.com/angular/angular/blob/a72ff8b055dbaef6134e28073eb0cd16034354d8/packages/common/package.json#L19) `*.mjs`

**Comment by denniskigen** [comment]
No, tried that already

**Comment by ibacher** [comment]
Did you also try switching the `import()` call to `require.context()` like we use in [apps](https://github.com/openmrs/openmrs-esm-core/blob/d7398a95e0efd782140a9fab5ddcf6549665d127/packages/apps/esm-login-app/src/index.ts#L11)? This is a bit of a reach because the ticket linked implies the same issue exists for `require.context()` but I want to be sure.

**Comment by ibacher** [comment]
Otherwise, I think it’s using the node_modules thing.

**Comment by denniskigen** [comment]
Is this the correct signature?

CleanShot 2023-10-12 at 9  36 14@2x

**Comment by denniskigen** [comment]
Actually, more worrying than this issue is the output I'm getting back from webpack after running `ng build --configuration=production`. It's not getting recognized as a federated module.

**Comment by denniskigen** [comment]
> Actually, more worrying than this issue is the output I'm getting back from webpack after running `ng build --configuration=production`. It's not getting recognized as a federated module.

Fixed in https://github.com/openmrs/openmrs-esm-patient-chart/pull/1414. It looks like what was needed was a few tweaks to `angular.json` and the custom webpack config in line with API changes in `ngx-build-plus`.

**Comment by denniskigen** [comment]
> Is this the correct signature?
> 
> CleanShot 2023-10-12 at 9  36 14@2x
> 
> If so, it yields a `Critical dependency: require function is used in a way in which dependencies cannot be statically extracted` warning but doesn't cause the build to error. Also, using the `node_modules` approach doesn't work.

This snippet seems to work. How can I test this fully? I've changed the locale to `FR` in the patient chart and it looks like buttons are getting translated correctly. Should I test for anything further than that? 

```ts
import(
  /* webpackInclude: /\.mjs$/ */
  /* webpackChunkName: "./assets/l10n/locales/[request]"*/
  `@/../../../node_modules/@angular/common/locales/${locale}.mjs`
).then((module) => registerLocaleData(module.default));
```

**Comment by ibacher** [comment]
> How can I test this fully?

AFAICT, we're only depending on this for date-related translations? E.g., the months of the year or days of the week. Maybe check a date picker?

**Comment by denniskigen** [comment]
Also, we should probably release `v4.0.0` of form entry and bump the library version in Patient Chart before merging this in.

**Comment by denniskigen** [comment]
Works great (see French date labels)

CleanShot 2023-10-14 at 11  17 31@2x

**Comment by denniskigen** [comment]
Should be good to go, @ibacher. The only thing I'd be worried about is the bump to `rxjs` (occasioned by the update to `@angular-extensions/elements`):

CleanShot 2023-10-14 at 11  37 48@2x

**Review by vasharma05 — APPROVED** [review]

**Pull request merged**
